version: '3'
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_SCHEMA_NAME}
      DB_USERNAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_USER_PASSWORD}
      TZ: ${TZ}

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

  db:
    image: mysql:8.0
    volumes:
      - php-sample-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}

volumes:
  php-sample-store:
